"""Add preview_data and agent_response fields

Revision ID: 6729811d7aa4
Revises: e73a10a3ec1b
Create Date: 2025-04-23 13:38:07.830123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6729811d7aa4'
down_revision = 'e73a10a3ec1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_status_summary',
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('status')
    )
    op.create_table('invoices_data',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('amount_total', sa.Float(), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('bill_to', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.String(length=50), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('agent_response', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('agent_response')
        batch_op.drop_column('preview_data')

    op.drop_table('invoices_data')
    op.drop_table('invoice_status_summary')
    # ### end Alembic commands ###
