"""Add final_data and status fields to Invoice

Revision ID: d97f25bf6aca
Revises: e2c90b39959c
Create Date: 2025-04-16 16:09:35.148142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd97f25bf6aca'
down_revision = 'e2c90b39959c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_data', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('final_data')

    # ### end Alembic commands ###
